### ISSUE TITLE
api一直无法获取vtb，搜索/VtbList列表为空

### ISSUE THREAD

**Issue by thouser8** [dd-center/bilibili-dd-monitor#16]
api似乎一直都无法获取到信息
![@(2D4X9PCF Q)XN3$2)SYL6](https://user-images.githubusercontent.com/83090571/147826918-eda62a14-df01-4c2a-aebd-068c873d7df2.png)
![image](https://user-images.githubusercontent.com/83090571/147826939-34af2707-60ea-4e16-88df-8c46d3e841a6.png)

**Comment by wdpm** [comment]
这种情况一般是服务器API无法返回数据导致的。

**Comment by thouser8** [comment]
> 

请问如何解决呢

**Comment by wdpm** [comment]
> 请问如何解决呢
1. 首先保证你的bilibili-dd-monitor 更新到最新版本。
2. 对于dd.center 服务器API无法返回数据的问题。你可以前往主 project 页面（例如：https://github.com/dd-center/vtbs.moe, 找这个人 simon3000）提交issue。一般而言，服务器API不会宕机，但是不保证绝对高可用。

**Comment by thouser8** [comment]
> > 请问如何解决呢
> 
> 1. 首先保证你的bilibili-dd-monitor 更新到最新版本。
> 2. 对于dd.center 服务器API无法返回数据的问题。你可以前往主 project 页面（例如：https://github.com/dd-center/vtbs.moe, 找这个人 simon3000）提交issue。一般而言，服务器API不会宕机，但是不保证绝对高可用。



> > 请问如何解决呢
> 
> 1. 首先保证你的bilibili-dd-monitor 更新到最新版本。
> 2. 对于dd.center 服务器API无法返回数据的问题。你可以前往主 project 页面（例如：https://github.com/dd-center/vtbs.moe, 找这个人 simon3000）提交issue。一般而言，服务器API不会宕机，但是不保证绝对高可用。

发现果然是因为中国移动网络无法访问https://api.vtbs.moe，使用全局/绕过大陆代理也一样。请问能否更改获取数据的api呢

**Comment by wdpm** [comment]
> > > 请问如何解决呢
> > 
> > 
> > 
> > 1. 首先保证你的bilibili-dd-monitor 更新到最新版本。
> > 2. 对于dd.center 服务器API无法返回数据的问题。你可以前往主 project 页面（例如：https://github.com/dd-center/vtbs.moe, 找这个人 simon3000）提交issue。一般而言，服务器API不会宕机，但是不保证绝对高可用。
> 
> > > 请问如何解决呢
> > 
> > 
> > 
> > 1. 首先保证你的bilibili-dd-monitor 更新到最新版本。
> > 2. 对于dd.center 服务器API无法返回数据的问题。你可以前往主 project 页面（例如：https://github.com/dd-center/vtbs.moe, 找这个人 simon3000）提交issue。一般而言，服务器API不会宕机，但是不保证绝对高可用。
> 
> 发现果然是因为中国移动网络无法访问[https://api.vtbs.moe，使用全局/绕过大陆代理也一样。请问能否更改获取数据的api呢](https://api.vtbs.moe%EF%BC%8C%E4%BD%BF%E7%94%A8%E5%85%A8%E5%B1%80/%E7%BB%95%E8%BF%87%E5%A4%A7%E9%99%86%E4%BB%A3%E7%90%86%E4%B9%9F%E4%B8%80%E6%A0%B7%E3%80%82%E8%AF%B7%E9%97%AE%E8%83%BD%E5%90%A6%E6%9B%B4%E6%94%B9%E8%8E%B7%E5%8F%96%E6%95%B0%E6%8D%AE%E7%9A%84api%E5%91%A2)

中国移动的问题之前simon3000就已经了解了。这个问题本质上还是服务器和网络的问题。
服务器是simon部署的，一共有3个：

- https://api.vtbs.moe （目前该程序一般默认是选择这个，除非这个没法ping）
- https://api.tokyo.vtbs.moe 
- https://vtbs.musedash.moe 
‘
实际上我也不清楚其他的节点中国移动能否访问。你可以去询问simon3000。如果你确定中国移动可以访问其他节点的话，
我可以考虑添加一个自定义API节点的设置功能。

**Comment by thouser8** [comment]
已经联系simon老哥解决问题~感谢你们
