### ISSUE TITLE
无法切换清晰度

### ISSUE THREAD

**Issue by thouser8** [dd-center/bilibili-dd-monitor#20]
选择清晰度无反应

**Comment by wdpm** [comment]
高清以上清晰度目前无法切换，这个bug早已发现和确认，但是个人没能找出问题的原因和解决方案，因此该bug被遗留下来。
猜测是chrominum内核版本或者player设置参数的问题。
如果你懂得如何修复，请告知我，或者直接pr。另外，给你个提示，可以借助浏览器console工具进行调试，你能看见错误的log。
目前我没法去调试这个项目。

**Comment by wdpm** [comment]
@[thouser8](https://github.com/thouser8)

为了验证这个问题：**未登录情况下能否切换到高清以上的清晰度**。
我在python中尝试了以下方式进行快速测试：
``` python
import webview

webview.create_window('test live quality',
                      'https://www.bilibili.com/blackboard/live/live-activity-player.html?enterTheRoom=0&cid=22301377')
webview.start()
```

在窗口中打开b站播放器自带的日志系统，捕获到了真正的原因。

![Snipaste_2022-02-16_15-57-35](https://user-images.githubusercontent.com/14016242/154221351-c75a707f-e6f1-4627-9c13-b52e15fe07de.png)

> user not login, reject  switch quality.

这个是b站系统给出的限制，因为游客身份在这种webview（浏览器情况下）是无法切换到高清以上清晰度的。
你可以复制这个链接：
> https://www.bilibili.com/blackboard/live/live-activity-player.html?enterTheRoom=0&cid=22301377
使用一个从未登陆过bilibili账号的浏览器进行访问，也能得到一致的结果。

结论：很遗憾，此问题对于游客身份无解。同时，该App不会计划去实现用户登录，因为这会涉及到隐私问题。

**Comment by wdpm** [comment]
@[thouser8](https://github.com/thouser8) 无法修复，关闭这个issue
