### ISSUE TITLE
VtbList列表为空，搜索也无果

### ISSUE THREAD

**Issue by a145600** [dd-center/bilibili-dd-monitor#4]
VtbList列表为空，搜索也无果，另外，可否自行添加监控直播间？

**Comment by wdpm** [comment]
> VtbList列表为空，搜索也无果

该项目目前使用的是vtbs.moe的 API作为数据接口，有时API出问题，就不会返回数据。

> 另外，可否自行添加监控直播间？

这个功能我以前也考虑过。不过我个人更倾向于修改 【Follow 页面的关注列表】作为API临时不可用的一种退化方案。
如下图所示：
![Snipaste_2021-03-11_11-46-57](https://user-images.githubusercontent.com/14016242/110733510-0b6c0800-8261-11eb-9f5a-78aefdebb68e.png)

1. API可用时，将你喜欢的vtb添加到Follow。
2. 当API不可用时，这样你依然可以在Follow页面点击：进入直播间。进入观看。此时的限制是，上图中红线划掉的部分将不可见，蓝色边框部分依然可用。

这样的功能你觉得可以吗？@a145600

**Comment by a145600** [comment]
> > VtbList列表为空，搜索也无果
> 
> 该项目目前使用的是vtbs.moe的 API作为数据接口，有时API出问题，就不会返回数据。
> 
> > 另外，可否自行添加监控直播间？
> 
> 这个功能我以前也考虑过。不过我个人更倾向于修改 【Follow 页面的关注列表】作为API临时不可用的一种退化方案。
> 如下图所示：
> ![Snipaste_2021-03-11_11-46-57](https://user-images.githubusercontent.com/14016242/110733510-0b6c0800-8261-11eb-9f5a-78aefdebb68e.png)
> 
> 1. API可用时，将你喜欢的vtb添加到Follow。
> 2. 当API不可用时，这样你依然可以在Follow页面点击：进入直播间。进入观看。此时的限制是，上图中红线划掉的部分将不可见，蓝色边框部分依然可用。
> 
> 这样的功能你觉得可以吗？@a145600


我觉得可能会存在几点问题：
1. 关注列表为空且API不可用时，无法自行添加关注也无法搜索关注，软件处于不可用状态
2. API可能存在想要关注而API接口数据未收录的vtb情况

**Comment by wdpm** [comment]
> 关注列表为空且API不可用时，无法自行添加关注也无法搜索关注，软件处于不可用状态

我上面提出的follow离线模式就是为了使得在api不可用时，依然保留对以前已关注vtb的进入直播间入口。这样，算是一种降级使用。当然，此时搜索功能肯定是不能用了。

> API可能存在想要关注而API接口数据未收录的vtb情况

同意。毕竟api有滞后性和不完善，手动添加直播间可以提高可用性。我现在想法是将其作为一个临时急救方案，当然直播间列表也会本地保存。但是不会和现有follow功能合并。

**Comment by wdpm** [comment]
follow离线模式被我舍弃，因为这个功能涉及太多代码逻辑改动。
手动添加直播间功能已实现。
@a145600

**Comment by wdpm** [comment]
@a145600 已处理，升级应用或者全新安装后可以看到。

概述：手动添加直播间，或者根据直播间号码关注用户（会丧失实时更新功能）。
