### ISSUE TITLE
vup无法搜索到

### ISSUE THREAD

**Issue by Zawinzala** [dd-center/bilibili-dd-monitor#5]
即使搜索的了新秀黑马主播，（已经直播了一个多月，经常榜单前三）
依然无法搜索到，比如“景礼”
建议优化搜索，除了名字至少应该支持直播间搜索vup然后可关注才对。

**Comment by wdpm** [comment]
目前该项目背后的数据API来自于dd-center的vdb项目。无法搜索代表该数据库并未收录。你可以：
- 走临时直播间快速入口，输入直播房间号
- 或者前往vdb项目进行反馈，补充未收录的vtuber。

@Zawinzala

**Comment by Zawinzala** [comment]
找到了似乎是手动更新VDB的网站：https://submit.vtbs.moe/edit

但是我依然建议可以直接搜索直播间并且关注（然后支持自定义主播备注）

现在的使用体验，显然不能当好一个好DD软件。

**Comment by wdpm** [comment]
关注直播间这个功能和关注vtuber功能存在较大重复。我可能不会考虑，抱歉。
另外，自定义主播备注这个功能（在原有关注vtuber的列表区域添加操作按钮）可以考虑。
@Zawinzala

**Comment by Zawinzala** [comment]
我的意思是，直接搜索直播间id来关注主播，你看一下这个项目：
https://github.com/congHu/DD_Monitor-android-kotlin
功能几乎一样，是用在安卓的。
（甚至名字都一样）

**Comment by wdpm** [comment]
我理解你的意思了。等我去探索一下再回复你吧。

**Comment by Zawinzala** [comment]
好耶ヽ(✿ﾟ▽ﾟ)ノ

**Comment by Zawinzala** [comment]
![image](https://user-images.githubusercontent.com/24386549/116566543-6ead1900-a939-11eb-888a-b5e0e55555c7.png)
上次vdb更新时间还是5天前，人工审核。。。。

我觉得这个数据库并不可靠和高效。

**Comment by wdpm** [comment]
概要设计：
1. 根据 https://api.live.bilibili.com/xlive/web-room/v1/index/getInfoByRoom?room_id=$roomId 链接获取vtuberInfo
2. 从response.data 中提取 room_info 以及 anchor_info 中需要的字段信息
3. 重构关注列表数据结构，将mids数组改为followVtbInfo数组，每个followVtbInfo包含vtuber名称，空间描述，vtuber头像url，直播间roomid。
旧的数据结构如下：
```
{
  "followLists": "[{\"id\":0,\"name\":\"默认分组\",\"mids\":[2299184,406805563,407106379,617459493]}]",
  "isNotifiedOnStart": true
}
```
 新数据结构（略）
4. 增添自定义主播备注功能。

理论上可以实现，就看什么时候有时间去写了。:smile: @Zawinzala.

**Comment by wdpm** [comment]
> ![image](https://user-images.githubusercontent.com/24386549/116566543-6ead1900-a939-11eb-888a-b5e0e55555c7.png)
> 上次vdb更新时间还是5天前，人工审核。。。。
> 
> 我觉得这个数据库并不可靠和高效。

对的。第三方都不太高效的，高效的还是bilibili官方源。所以，实际上，我是支持你提出的上面的功能需求的。要是我d的是小众的没收录的，估计这功能我早写了。

**Comment by wdpm** [comment]
@Zawinzala 已处理，升级应用或者全新安装后可以看到。
